const TOTAL = 300;
const SCENE_SECONDS = 15;
let running=false, paused=false, muted=false, elapsed=0, sceneIndex=-1, timer=null, sceneTimers=[], fontMode=0;
const $=s=>document.querySelector(s);

const rows=(items)=>`<table class="table"><thead><tr><th>Paciente</th><th>Detalle</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td><span class="tag ${i===2?'warn':''}">${x[3]}</span></td><td>•••</td></tr>`).join('')}</tbody></table>`;
const side=(active,role='Administración')=>`<aside class="sidebar"><div class="side-brand"><span>S</span> SICM</div>${[['⌂','Inicio'],['♙','Pacientes'],['▣','Citas'],['✚','Historia clínica'],['▤','Recetas'],['◈','Enfermería'],['♢','Reportes'],['♧','Notificaciones'],['⚙','Configuración']].map(n=>`<div class="navitem ${n[1]===active?'active':''}"><b>${n[0]}</b>${n[1]}</div>`).join('')}<div class="side-user">● Sesión segura<br><b>${role}</b></div></aside>`;
const head=(title,sub,role)=>`<div class="page-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="avatar"><i>${role[0]}</i><span><b>${role}</b><br>Centro médico</span></div></div>`;
const shell=(active,title,sub,role,body)=>`<div class="shell">${side(active,role)}<section class="content">${head(title,sub,role)}${body}</section></div>`;
const stats=()=>`<div class="stats"><div class="stat"><small>Citas de hoy</small><strong>24</strong><em>↑ 12% esta semana</em></div><div class="stat"><small>Pacientes activos</small><strong>1.248</strong><em>↑ 18 nuevos</em></div><div class="stat"><small>Atenciones pendientes</small><strong>08</strong><em>Dentro del horario</em></div><div class="stat"><small>Inventario crítico</small><strong>03</strong><em style="color:#bd7435">Requiere revisión</em></div></div>`;

const scenes=[
{name:'Inicio de sesión',k:'ACCESO SEGURO',title:'Inicio de sesión por rol',cursor:[68,56],
speech:'Bienvenidos a SICM. Cada usuario inicia sesión con sus credenciales y el sistema muestra únicamente las funciones autorizadas para su rol. La versión validada mantiene acceso seguro, permisos diferenciados y una opción de tamaño de texto para mejorar la legibilidad.',
render:()=>`<div class="login"><div class="login-intro"><div class="mini-brand"><em>S</em><span><b>SICM</b><br><small>Centro médico inteligente</small></span></div><h1>Inicio de sesión<br>del centro médico</h1><p>Acceso seguro y personalizado para profesionales, pacientes y colaboradores.</p><div class="role-card"><b>Administración</b><span>Supervisa indicadores, usuarios y operación general.</span></div></div><div class="login-form"><div class="field"><label>Tipo de usuario</label><div class="fieldbox">Administración⌄</div></div><div class="field"><label>Usuario</label><div id="userValue" class="fieldbox"></div></div><div class="field"><label>Contraseña</label><div id="passValue" class="fieldbox"></div></div><button class="primary">Ingresar</button><div class="notice">A+ permite ampliar la visualización durante la demostración.</div></div></div>`,actions:loginActions},

{name:'Panel principal',k:'VISIÓN GENERAL',title:'Panel principal del sistema',cursor:[42,44],
speech:'Después del acceso aparece el panel principal. Aquí se consultan las citas, pacientes activos, atenciones pendientes y alertas de inventario. Los reportes se generan con la información registrada por cada área y permiten una supervisión rápida de la operación.',
render:()=>shell('Inicio','Buenos días, Ana','Resumen operativo del centro médico','Administración',`${stats()}<div class="grid2"><div class="card"><h3>Atenciones de la semana</h3><div class="chart">${[54,72,44,86,65,92,76].map(x=>`<i style="height:${x}%"></i>`).join('')}</div></div><div class="card"><h3>Actividad reciente</h3>${['Nueva cita registrada','Historia clínica actualizada','Medicamento entregado','Pago confirmado'].map((x,i)=>`<div class="activity"><i>${['▣','✚','◈','✓'][i]}</i><span><b>${x}</b><br>Hace ${i+2} minutos</span></div>`).join('')}</div></div>`)},

{name:'Datos del paciente',k:'ROL PACIENTE',title:'Datos personales y contacto de emergencia',cursor:[57,44],
speech:'El paciente puede actualizar sus datos personales. La validación incorporó identificación por cédula o pasaporte, datos de representante cuando se trata de un menor de edad, teléfono de emergencia y límites claros para reducir errores de digitación.',
render:()=>shell('Pacientes','Mi perfil','Actualización segura de información personal','Paciente',`<div class="role-banner"><div><h3>Perfil del paciente</h3><p>Datos personales, identificación y contacto de emergencia.</p></div><span>✓ Identidad verificada</span></div><div class="card"><div class="panel-form"><div class="fake-input">Tipo: Cédula / Pasaporte</div><div class="fake-input">Identificación: 0912345678</div><div class="fake-input">Nacimiento: 14/05/1992</div><div class="fake-input">Teléfono: 0984567821 · 10 dígitos</div><div class="fake-input">Emergencia: 0991234567</div><div class="fake-input">Menor de edad: No</div><div class="fake-input wide">Dirección: Av. Central 145, Guayaquil</div></div><div style="text-align:right;margin-top:12px"><button class="btn">Guardar cambios</button></div><div class="notice">✓ Datos actualizados correctamente.</div></div>`)},

{name:'Citas del paciente',k:'ROL PACIENTE',title:'Profesional, horarios, pagos y vista mensual',cursor:[31,45],
speech:'Al solicitar una cita, el paciente puede elegir especialidad y profesional, revisar horarios disponibles y alternar entre vista por día, semana o mes. También consulta pagos y comprobantes desde su propio portal.',
render:()=>shell('Citas','Mis citas','Agenda personal y pagos','Paciente',`<div class="tabs"><span>Día</span><span>Semana</span><span class="active">Mes</span><span>Pagos y comprobantes</span></div><div class="toolbar"><div class="search">Especialidad: Odontología · Profesional: Dra. Paredes</div><button class="btn">+ Solicitar cita</button></div>${rows([['Valeria Vera','Odontología · Dra. Paredes','12 Ago · 09:30','Confirmada'],['Valeria Vera','Medicina general · Dr. Rojas','18 Ago · 11:00','Programada'],['Valeria Vera','Nutrición · Lic. Bravo','26 Ago · 15:30','Pendiente']])}<div class="grid2"><div class="card"><h3>Horarios disponibles</h3><div class="notice">09:30 · 10:15 · 11:00 · 14:00</div></div><div class="card"><h3>Pagos</h3><p style="font-size:9px">Último comprobante: #REC-2026-194</p><strong style="font-size:22px">$ 0,00</strong></div></div>`)},

{name:'Recepción y búsqueda',k:'RECEPCIÓN',title:'Registro y búsqueda flexible de pacientes',cursor:[78,33],
speech:'Recepción busca pacientes por nombre, cédula, pasaporte o teléfono y puede actualizar únicamente los datos administrativos autorizados. El historial clínico permanece protegido y separado de las tareas de recepción.',
render:()=>shell('Pacientes','Pacientes','Registro y consulta administrativa','Recepción',`<div class="toolbar"><div class="search">⌕ Buscar por nombre, cédula, pasaporte o teléfono</div><button class="btn alt">Filtros</button><button class="btn">+ Nuevo paciente</button></div>${rows([['Carlos Mendoza','CI 0917482931 · 39 años','Hoy · 08:10','Activo'],['María Zambrano','Pasaporte P1234567 · 27 años','Ayer · 16:42','Activo'],['José Castillo','CI 0929384712 · 51 años','28 Jul · 10:20','Revisión'],['Ana Torres','CI 0911255890 · 44 años','25 Jul · 14:05','Activo']])}`)},

{name:'Agenda médica',k:'RECEPCIÓN',title:'Disponibilidad por profesional y vista mensual',cursor:[69,54],
speech:'La agenda muestra disponibilidad por profesional y evita cruces de horarios. Recepción puede cambiar una cita o cancelarla y el paciente recibe una notificación. La validación incorporó una vista mensual para facilitar la planificación.',
render:()=>shell('Citas','Agenda médica','Programación coordinada por especialidad','Recepción',`<div class="tabs"><span>Día</span><span>Semana</span><span class="active">Mes</span></div><div class="toolbar"><button class="btn alt">‹ Agosto</button><div class="search">Profesional: Dra. Paredes · Odontología</div><button class="btn">+ Agendar cita</button></div><div class="calendar">${['Hora','Lun 04','Mar 05','Mié 06','Jue 07','Vie 08','08:00','Med. General','','Odontología','','Nutrición','09:00','','Psicología','Enfermería','Odontología','','10:00','Terapia física','','Med. General','','Psicología','11:00','','Nutrición','','Terapia física','Odontología'].map((x,i)=>`<div class="${i>5&&x?'appt':''}">${x}</div>`).join('')}</div>`)},

{name:'Pagos y comprobantes',k:'RECAUDACIÓN',title:'Cobros asociados a la atención',cursor:[71,60],
speech:'Recaudación registra el pago asociado a la cita, selecciona la forma de pago y genera un comprobante. El paciente puede consultar posteriormente el estado de sus pagos desde su portal.',
render:()=>shell('Inicio','Registro de cobro','Comprobante asociado a la atención','Recaudación',`<div class="grid2"><div class="card"><h3>Detalle del servicio</h3><div class="panel-form"><div class="fake-input wide">Paciente: Carlos Mendoza</div><div class="fake-input wide">Servicio: Consulta de medicina general</div><div class="fake-input">Valor: $ 25,00</div><div class="fake-input">Descuento: $ 0,00</div><div class="fake-input">Total: $ 25,00</div><div class="fake-input wide">Forma de pago: Tarjeta / Transferencia / Efectivo</div></div><button class="btn" style="margin-top:12px;width:100%">Registrar pago y emitir comprobante</button></div><div class="card"><h3>Resumen</h3><strong style="font-size:27px">$ 25,00</strong><div class="notice">✓ Pago asociado a la cita #AT-2026-00891</div><div class="notice">Comprobante disponible para el paciente.</div></div></div>`)},

{name:'Triage de enfermería',k:'ENFERMERÍA',title:'Signos vitales y nota de enfermería',cursor:[48,60],
speech:'En enfermería se realiza la valoración inicial. Además de presión, temperatura, pulso, peso y talla, la versión validada registra frecuencia respiratoria y saturación de oxígeno. También permite dejar una nota de enfermería con el procedimiento realizado.',
render:()=>shell('Enfermería','Valoración de enfermería','Paciente: Carlos Mendoza · Cita 08:30','Enfermería',`<div class="role-banner"><div><h3>Triage en curso</h3><p>Valoración previa a consulta.</p></div><span>08:17</span></div><div class="card"><h3>Signos vitales</h3><div class="panel-form"><div class="fake-input">Presión: 120 / 80 mmHg</div><div class="fake-input">Temperatura: 36,7 °C</div><div class="fake-input">Pulso: 76 lpm</div><div class="fake-input">Frecuencia respiratoria: 18 rpm</div><div class="fake-input">Saturación O₂: 98%</div><div class="fake-input">Dolor: 2 / 10</div><div class="fake-input wide">Nota de enfermería: paciente consciente, orientado. Procedimiento realizado sin novedades.</div></div><div style="text-align:right;margin-top:11px"><button class="btn">Guardar valoración y nota</button></div></div>`)},

{name:'Receta hacia Enfermería',k:'MEDICINA GENERAL / ODONTOLOGÍA',title:'Receta electrónica enviada a Enfermería',cursor:[71,62],
speech:'Los profesionales de medicina general y odontología pueden emitir recetas. Al firmarlas, el sistema las envía directamente a Enfermería para su verificación y entrega, manteniendo trazabilidad entre prescripción y suministro.',
render:()=>shell('Recetas','Nueva receta médica','Paciente: Carlos Mendoza · Sin alergias registradas','Medicina general',`<div class="card"><h3>Tratamiento farmacológico</h3><div class="med-row"><b>Amoxicilina 500 mg</b><span>Oral · cada 8 h</span><span>7 días</span><span>✎</span></div><div class="med-row"><b>Ibuprofeno 400 mg</b><span>Oral · cada 12 h</span><span>5 días</span><span>✎</span></div><div class="notice">✓ No se detectaron alergias ni interacciones críticas.</div><button class="btn" style="width:100%">Firmar y enviar a Enfermería</button></div>`)},

{name:'Entrega de medicamentos',k:'ENFERMERÍA',title:'Confirmación de medicamento entregado',cursor:[65,57],
speech:'Enfermería recibe la receta, verifica paciente, medicamento, dosis y cantidad, y después marca cada medicamento como entregado. Queda registrada la fecha, la persona responsable y cualquier observación.',
render:()=>shell('Recetas','Recetas por entregar','Validación segura de medicamentos','Enfermería',`<div class="card"><h3>RX-2026-0174 · Carlos Mendoza</h3><div class="med-row"><b>Amoxicilina 500 mg</b><span>Cada 8 horas</span><span>21 cápsulas</span><span class="tag">Verificada</span></div><div class="med-row"><b>Ibuprofeno 400 mg</b><span>Cada 12 horas</span><span>10 tabletas</span><span class="tag">Verificada</span></div><div class="notice">Receta recibida desde Medicina General.</div><button class="btn">Marcar medicamento entregado</button><span class="tag info" style="margin-left:8px">Responsable y hora quedan registrados</span></div>`)},

{name:'Historia por especialidad',k:'HISTORIA CLÍNICA',title:'Historial filtrado por especialidad',cursor:[55,57],
speech:'La historia clínica integra las atenciones, pero ahora permite filtrar por especialidad para evitar mezclar información de distintas áreas. Los profesionales pueden revisar la evolución pertinente y registrar nueva información según sus permisos.',
render:()=>shell('Historia clínica','Historia clínica electrónica','Paciente: Carlos Mendoza · HC-001248','Medicina general',`<div class="tabs"><span class="active">Medicina general</span><span>Odontología</span><span>Psicología</span><span>Nutrición</span><span>Terapia física</span></div><div class="card"><div class="panel-form"><div class="fake-input wide">Motivo: dolor de garganta y fiebre.</div><div class="fake-input wide">Diagnóstico: faringoamigdalitis aguda.</div><div class="fake-input wide">Evolución: respuesta favorable al tratamiento.</div></div><div style="text-align:right;margin-top:10px"><button class="btn alt">Guardar borrador</button> <button class="btn">Firmar atención</button></div></div>`)},

{name:'Odontología',k:'ODONTOLOGÍA',title:'Odontograma y receta integrada',cursor:[54,60],
speech:'Odontología dispone de odontograma para registrar caries, restauraciones, piezas extraídas y coronas. El profesional registra procedimientos e indicaciones y, cuando corresponde, puede emitir una receta que se deriva a Enfermería.',
render:()=>shell('Historia clínica','Odontología','Odontograma clínico · Valeria Vera','Odontología',`<div class="grid2"><div class="card"><h3>Odontograma</h3><div class="tooth-map">${Array.from({length:32},(_,i)=>`<div class="tooth ${[3,14,18,27].includes(i)?'done':''}">${i<16?18-i:i+17}</div>`).join('')}</div><div class="notice">Caries · Restauración · Extraído · Corona.</div></div><div class="card"><h3>Procedimiento de hoy</h3><div class="fake-input">Pieza: 18 · Exodoncia simple</div><div class="fake-input wide" style="margin-top:8px">Observación: procedimiento sin complicaciones.</div><button class="btn" style="width:100%;margin-top:10px">Registrar procedimiento</button><button class="btn alt" style="width:100%;margin-top:7px">Emitir receta a Enfermería</button></div></div>`)},

{name:'Psicología',k:'PSICOLOGÍA',title:'Antecedentes y objetivo terapéutico',cursor:[60,58],
speech:'Psicología mantiene las notas sensibles con acceso restringido. La validación añadió antecedentes psicológicos previos y un objetivo terapéutico explícito, además de evolución, intervención y programación del seguimiento.',
render:()=>shell('Historia clínica','Consulta psicológica','Seguimiento terapéutico · María Zambrano','Psicología',`<div class="role-banner"><div><h3>Nota clínica confidencial</h3><p>Acceso restringido a profesionales autorizados.</p></div><span>🔒 Protegido</span></div><div class="card"><div class="panel-form"><div class="fake-input wide">Antecedentes previos: tratamiento psicológico hace dos años.</div><div class="fake-input wide">Objetivo terapéutico: reducir síntomas de ansiedad y mejorar afrontamiento.</div><div class="fake-input wide">Intervención: respiración y reestructuración cognitiva.</div><div class="fake-input wide">Plan: control en catorce días.</div></div><button class="btn" style="float:right;margin-top:10px">Guardar evolución</button></div>`)},

{name:'Nutrición',k:'NUTRICIÓN',title:'Evaluación y plan nutricional',cursor:[63,61],
speech:'Nutrición registra medidas antropométricas, hábitos, objetivos y un plan nutricional individual. Las indicaciones quedan disponibles para el paciente y forman parte de la historia clínica de la especialidad.',
render:()=>shell('Historia clínica','Evaluación nutricional','Plan individual · Ana Torres','Nutrición',`<div class="stats"><div class="stat"><small>Peso</small><strong>68,4</strong><em>kg</em></div><div class="stat"><small>Estatura</small><strong>1,64</strong><em>m</em></div><div class="stat"><small>IMC</small><strong>25,4</strong><em style="color:#b57b3b">Sobrepeso leve</em></div><div class="stat"><small>Meta</small><strong>64,0</strong><em>12 semanas</em></div></div><div class="grid2"><div class="card"><h3>Plan nutricional</h3><div class="notice">Plan individual con metas y hábitos alimentarios.</div></div><div class="card"><h3>Próximo control</h3><p style="font-size:10px">26 de agosto · 15:30</p><button class="btn" style="width:100%">Publicar indicaciones</button></div></div>`)},

{name:'Terapia física',k:'TERAPIA FÍSICA',title:'Sesión, duración, prioridad y ejercicios',cursor:[57,62],
speech:'Terapia Física registra el número de sesión, prioridad, duración, ejercicios y evolución. También puede consultar reportes para seguir el avance del plan de rehabilitación y documentar objetivamente la recuperación.',
render:()=>shell('Historia clínica','Sesión de terapia física','Rehabilitación de rodilla · José Castillo','Terapia física',`<div class="role-banner"><div><h3>Sesión 5 de 10 · Prioridad media</h3><p>Duración planificada: 40 minutos.</p></div><div class="metric-ring"></div></div><div class="grid2"><div class="card"><h3>Evaluación</h3><div class="fake-input">Dolor: 3 / 10 · Flexión: 118°</div><div class="fake-input wide" style="margin-top:8px">Evolución: mejora progresiva de movilidad.</div></div><div class="card"><h3>Ejercicios</h3>${['Movilidad articular · 10 min','Fortalecimiento · 20 min','Propiocepción · 10 min'].map(x=>`<div class="notice">✓ ${x}</div>`).join('')}<button class="btn">Registrar sesión</button> <button class="btn alt">Ver reportes</button></div></div>`)},

{name:'Derivaciones',k:'ATENCIÓN MULTIDISCIPLINARIA',title:'Derivación con contexto clínico',cursor:[58,50],
speech:'Cuando un profesional deriva a otra especialidad, registra área de origen, destino, motivo, prioridad y un resumen clínico. Así el área receptora recibe contexto suficiente antes de atender al paciente.',
render:()=>shell('Historia clínica','Nueva derivación','Paciente: Carlos Mendoza','Medicina general',`<div class="card"><h3>Derivación interna</h3><div class="panel-form"><div class="fake-input">Origen: Medicina general</div><div class="fake-input">Destino: Nutrición</div><div class="fake-input">Prioridad: Media</div><div class="fake-input wide">Motivo: control de peso y hábitos asociados.</div><div class="fake-input wide">Resumen clínico para área receptora: paciente estable; considerar antecedentes y tratamiento vigente.</div></div><div style="text-align:right;margin-top:10px"><button class="btn">Enviar derivación</button></div></div>`)},

{name:'Notificaciones y accesibilidad',k:'COMUNICACIÓN',title:'Avisos, confirmaciones y dictado por voz',cursor:[64,50],
speech:'El sistema envía avisos por citas, cambios, cancelaciones, recetas e indicaciones. Los mensajes de confirmación son más claros y se incorpora dictado por voz como apoyo de accesibilidad en campos de texto compatibles.',
render:()=>shell('Notificaciones','Centro de notificaciones','Comunicación con pacientes y personal','Recepción',`<div class="grid2"><div class="card"><h3>Nueva notificación</h3><div class="fake-input">Destinatario: Valeria Vera</div><div class="fake-input" style="margin-top:8px">Canal: Correo electrónico y portal</div><div class="fake-input wide" style="margin-top:8px">Su cita de odontología fue confirmada para el 12 de agosto a las 09:30.</div><div style="margin-top:9px"><span class="voice-chip">🎙 Dictar mensaje</span> <button class="btn">Enviar notificación</button></div></div><div class="card"><h3>Confirmaciones</h3>${['Cita confirmada · Entregada','Receta disponible · Leída','Cambio de horario · Entregada','Recordatorio · Pendiente'].map((x,i)=>`<div class="activity"><i>${i<3?'✓':'…'}</i><span><b>${x.split(' · ')[0]}</b><br>${x.split(' · ')[1]}</span></div>`).join('')}</div></div>`)},

{name:'Coordinación',k:'COORDINACIÓN',title:'Profesionales, horarios y permisos',cursor:[44,48],
speech:'Coordinación administra profesionales, horarios y permisos operativos sin alterar los datos clínicos. Puede consultar reportes por área y supervisar la disponibilidad del centro médico.',
render:()=>shell('Configuración','Coordinación operativa','Supervisión de servicios y profesionales','Coordinación',`<div class="role-banner"><div><h3>Perfil de supervisión</h3><p>Gestión operativa sin edición clínica.</p></div><span>Permisos controlados</span></div>${stats()}<div class="grid2"><div class="card"><h3>Profesionales y cobertura</h3>${['Medicina general · Dra. Rojas · Disponible','Odontología · Dra. Paredes · Disponible','Psicología · Lic. Andrade · 14:00','Terapia física · Lic. Vera · 15:30'].map(x=>`<div class="notice">${x}</div>`).join('')}</div><div class="card"><h3>Acciones</h3><button class="btn alt" style="width:100%;margin:4px">Editar profesionales y horarios</button><button class="btn alt" style="width:100%;margin:4px">Gestionar usuarios y roles</button><button class="btn alt" style="width:100%;margin:4px">Consultar reportes</button></div></div>`)},

{name:'Reportes y auditoría',k:'ADMINISTRACIÓN',title:'Reportes automáticos por área',cursor:[58,47],
speech:'Los reportes consolidan automáticamente las atenciones registradas por Medicina General, Odontología, Enfermería, Psicología, Nutrición y Terapia Física. La auditoría conserva accesos y operaciones críticas para mantener trazabilidad.',
render:()=>shell('Reportes','Reportes y auditoría','Indicadores consolidados del centro médico','Administración',`<div class="stats"><div class="stat"><small>Medicina general</small><strong>142</strong><em>atenciones</em></div><div class="stat"><small>Odontología</small><strong>86</strong><em>atenciones</em></div><div class="stat"><small>Enfermería</small><strong>174</strong><em>procedimientos</em></div><div class="stat"><small>Terapia física</small><strong>64</strong><em>sesiones</em></div></div><div class="grid2"><div class="card"><h3>Atenciones por especialidad</h3><div class="chart">${[93,77,64,52,48,71,59].map(x=>`<i style="height:${x}%"></i>`).join('')}</div></div><div class="card"><h3>Registro de auditoría</h3>${['Historia clínica consultada','Receta firmada y enviada','Medicamento marcado entregado','Reporte mensual exportado'].map((x,i)=>`<div class="activity"><i>✓</i><span><b>${x}</b><br>Usuario autorizado · ${10+i}:2${i}</span></div>`).join('')}</div></div>`)},

{name:'Cierre',k:'SICM',title:'Prototipo actualizado con validación',cursor:[50,50],
speech:'SICM integra pacientes, recepción, recaudación, enfermería, medicina general, odontología, psicología, nutrición, terapia física y coordinación. Esta versión incorpora las principales observaciones de la validación walkthrough manteniendo la estructura visual del prototipo. Gracias por conocer SICM.',
render:()=>`<div style="height:100%;display:grid;place-items:center;background:radial-gradient(circle at 50% 30%,#e9f8f5,#fff)"><div style="text-align:center;max-width:690px"><div class="hero-icon">S</div><small style="letter-spacing:.2em;color:#398c82;font-weight:700">PROTOTIPO FINAL VALIDADO</small><h1 style="font:800 clamp(38px,5vw,68px)/1 Manrope;letter-spacing:-.05em;margin:15px 0">Una atención conectada,<br>segura y trazable.</h1><p style="color:#617775;font-size:14px;line-height:1.6">La demostración incorpora las principales mejoras solicitadas durante los walkthrough sin modificar la estructura general de SICM.</p><div class="feature-row" style="color:#315e5a"><span>✓ Roles y permisos</span><span>✓ Historia por especialidad</span><span>✓ Recetas a Enfermería</span><span>✓ Reportes automáticos</span></div></div></div>`}
];

function clearSceneTimers(){sceneTimers.forEach(x=>{clearTimeout(x);clearInterval(x)});sceneTimers=[]}
function later(fn,ms){sceneTimers.push(setTimeout(fn,ms))}
function moveCursor(x,y,click=false){const c=$('#cursor');c.style.left=x+'%';c.style.top=y+'%';if(click)later(()=>{const fx=$('#clickFx');fx.style.left=`calc(${x}% + 3px)`;fx.style.top=`calc(${y}% + 5px)`;fx.classList.remove('go');void fx.offsetWidth;fx.classList.add('go')},950)}
function highlight(x,y,w=17,h=8){const s=$('#spotlight');s.style.left=x+'%';s.style.top=y+'%';s.style.width=w+'%';s.style.height=h+'%';s.classList.add('show');later(()=>s.classList.remove('show'),2600)}
function loginActions(){const type=(el,text,step)=>{let i=0;const t=setInterval(()=>{if(paused)return;el.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(t)},step);sceneTimers.push(t)};later(()=>{moveCursor(70,47,true);highlight(59,42,29,8);type($('#userValue'),'admin',180)},1300);later(()=>{moveCursor(70,59,true);highlight(59,54,29,8);type($('#passValue'),'••••••••',140)},4300);later(()=>{moveCursor(72,70,true);highlight(59,65,29,8)},7600)}
function speak(text){if(muted||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.rate=.96;u.pitch=1;u.volume=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^es[-_]/i.test(v.lang)&&/female|paulina|monica|helena|sabina|soledad/i.test(v.name))||voices.find(v=>/^es/i.test(v.lang))||null;speechSynthesis.speak(u)}
function showScene(i){clearSceneTimers();sceneIndex=i;const sc=scenes[i],browser=$('#browser');browser.classList.add('fade');setTimeout(()=>{$('#screen').innerHTML=sc.render();browser.classList.remove('fade','ken');void browser.offsetWidth;browser.classList.add('ken');$('#sceneName').textContent=sc.name;$('#chapterKicker').textContent=sc.k;$('#chapterTitle').textContent=sc.title;const ch=$('#chapter');ch.classList.add('show');setTimeout(()=>ch.classList.remove('show'),2800);moveCursor(sc.cursor[0],sc.cursor[1]);later(()=>highlight(sc.cursor[0]-7,sc.cursor[1]-3),4300);later(()=>moveCursor(Math.min(82,sc.cursor[0]+9),Math.min(76,sc.cursor[1]+10),true),7200);if(sc.actions)sc.actions();speak(sc.speech)},420)}
function tick(){if(!running||paused)return;elapsed=Math.min(TOTAL,elapsed+.25);const i=Math.min(scenes.length-1,Math.floor(elapsed/SCENE_SECONDS));if(i!==sceneIndex)showScene(i);$('#progress').style.width=(elapsed/TOTAL*100)+'%';const f=n=>String(n).padStart(2,'0');$('#clock').textContent=`${f(Math.floor(elapsed/60))}:${f(Math.floor(elapsed%60))} / 05:00`;if(elapsed>=TOTAL){running=false;clearInterval(timer);$('#pauseBtn').textContent='Reiniciar';if('speechSynthesis'in window)speechSynthesis.cancel()}}
function start(){if(running)return;$('#welcome').classList.add('hidden');elapsed=0;sceneIndex=-1;running=true;paused=false;$('#pauseBtn').textContent='Pausar';tick();timer=setInterval(tick,250)}
$('#startBtn').onclick=start;
$('#pauseBtn').onclick=()=>{if(!running){start();return}paused=!paused;$('#pauseBtn').textContent=paused?'Continuar':'Pausar';if('speechSynthesis'in window){if(paused)speechSynthesis.pause();else speechSynthesis.resume()}};
$('#soundBtn').onclick=()=>{muted=!muted;$('#soundBtn').textContent=muted?'🔇':'🔊';if('speechSynthesis'in window){if(muted)speechSynthesis.cancel();else speak(scenes[sceneIndex]?.speech||'Narración activada.')}};
$('#fontBtn').onclick=()=>{fontMode=(fontMode+1)%3;document.body.classList.remove('font-large','font-xlarge');if(fontMode===1)document.body.classList.add('font-large');if(fontMode===2)document.body.classList.add('font-xlarge');$('#fontBtn').textContent=fontMode===0?'A+':fontMode===1?'A++':'A'};
$('#fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
$('#markers').innerHTML=scenes.map(()=>'<i></i>').join('');
window.addEventListener('beforeunload',()=>{if('speechSynthesis'in window)speechSynthesis.cancel()});
